src/FAPROD/BookingBundle/Entity/Booking.php
<?php

namespace FAPROD\BookingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use FAPROD\CoreBundle\Lib\MyConst;


/**
 * @ORM\Entity(repositoryClass="FAPROD\BookingBundle\Entity\BookingRepository")
 * @ORM\HasLifecycleCallbacks() 
 * @ORM\Table(name="booking")
 */
class Booking
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="FAPROD\UserBundle\Entity\User", inversedBy="bookings1")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $user;
	
	/**
     * @ORM\ManyToOne(targetEntity="FAPROD\UserBundle\Entity\User", inversedBy="bookings2")
     * @ORM\JoinColumn(name="seller_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $seller;
	
	/**
     * @ORM\ManyToOne(targetEntity="FAPROD\UserBundle\Entity\Offer")
     * @ORM\JoinColumn(name="offer_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $offer;
        
	/**
     * @ORM\Column(name="statut", type="integer", nullable=true)
     */
    private $statut;
	
	/**
     * @ORM\Column(name="price", type="float", nullable=true)
     */
    private $price;
	
	/**
     * @ORM\Column(name="code", type="string", length=50, nullable=true)
     */
    private $code;
    
    /**
     * @ORM\Column(name="code_reduc", type="float", nullable=true)
     */
    private $code_reduc;
	
	/**
     * @ORM\Column(name="commission", type="float", nullable=true)
     */
    private $commission;
	
	/**
     * @ORM\Column(name="tva", type="float", nullable=true)
     */
    private $tva;
	
	/**
     * @ORM\Column(name="price_ttc", type="float", nullable=true)
     */
    private $price_ttc;
	
	/**
     * @ORM\Column(name="PreauthorizationId", type="integer", nullable=true)
     */
    private $PreauthorizationId;
	
	/**
     * @ORM\Column(name="CardId", type="integer", nullable=true)
     */
    private $CardId;
	
	/**
     * @ORM\Column(name="date_rdv", type="datetime", nullable=true)
     */
    private $date_rdv;
	
	/**
     * @ORM\Column(name="heure_rdv", type="integer", nullable=true)
     */
    private $heure_rdv;
	
	/**
     * @ORM\Column(name="minute_rdv", type="integer", nullable=true)
     */
    private $minute_rdv;
    
    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $created_at;
    
    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;


    // Les getters et setters
    
    /**
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps()
    {
        $this->setUpdatedAt(new \DateTime('now'));
    
        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }


    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    public function getUpdatedAt($format = '')
    {
        if($this->updated_at and $this->updated_at instanceof \DateTime and $format){
            return $this->updated_at->format($format);
        } else {
            return $this->updated_at;
        }      
    }

    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    public function getCreatedAt($format = '')
    {
        if($this->created_at and $this->created_at instanceof \DateTime and $format){
            return $this->created_at->format($format);
        } else {
            return $this->created_at;
        }
    }

    public function getId()
    {
        return $this->id;
    }

    public function setUser(\FAPROD\UserBundle\Entity\User $user)
    {
        $this->user = $user;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }
    
    public function setSeller(\FAPROD\UserBundle\Entity\User $seller)
    {
        $this->seller = $seller;

        return $this;
    }

    public function getSeller()
    {
        return $this->seller;
    }
	
	public function setStatut($statut)
    {
        $this->statut = $statut;

        return $this;
    }

    public function getStatut()
    {
        return $this->statut;
    }
	
	public function getStatutLabel()
    {
        return MyConst::getBookingStatutLabel($this->statut);
    }
	
	public function setPreauthorizationId($PreauthorizationId)
    {
        $this->PreauthorizationId = $PreauthorizationId;

        return $this;
    }

    public function getPreauthorizationId()
    {
        return $this->PreauthorizationId;
    }
	
	public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    public function getPrice()
    {
        return $this->price;
    }
	
	public function getPriceLabel()
    {
       if ($this->getPrice())
          return number_format($this->getPrice(), 0, '.', ' ').' €';
       else return '';
    }
	
    public function setOffer(\FAPROD\UserBundle\Entity\Offer $offer = null)
    {
        $this->offer = $offer;

        return $this;
    }

    public function getOffer()
    {
        return $this->offer;
    }

    public function setCommission($commission)
    {
        $this->commission = $commission;

        return $this;
    }

    public function getCommission()
    {
        return $this->commission;
    }
	
	public function getCommissionLabel()
    {
       if ($this->getCommission())
          return number_format($this->getCommission(), 0, '.', ' ').' €';
       else return '';
    }

    public function setTva($tva)
    {
        $this->tva = $tva;

        return $this;
    }

    public function getTva()
    {
        return $this->tva;
    }
	
	public function getTvaLabel()
    {
       if ($this->getTva())
          return number_format($this->getTva(), 0, '.', ' ').' €';
       else return '';
    }

    public function setPriceTtc($priceTtc)
    {
        $this->price_ttc = $priceTtc;

        return $this;
    }

    public function getPriceTtc()
    {
        return $this->price_ttc;
    }
	
	public function getPriceTtcLabel()
    {
       if ($this->getPriceTtc())
          return number_format($this->getPriceTtc(), 0, '.', ' ').' €';
       else return '';
    }

    public function setDateRdv($dateRdv)
    {
        $this->date_rdv = $dateRdv;

        return $this;
    }
	
	public function getDateRdv($format = '')
    {
    	if($this->date_rdv and $this->date_rdv instanceof \DateTime and $format){
		    return $this->date_rdv->format($format);
		} else {
    		return $this->date_rdv;
    	}
    }

    public function setHeureRdv($heureRdv)
    {
        $this->heure_rdv = $heureRdv;

        return $this;
    }

    public function getHeureRdv()
    {
        return $this->heure_rdv;
    }
	
	public function getHeureRdvLabel()
    {
        return $this->heure_rdv.'h'.$this->minute_rdv;
    }

    public function setCardId($cardId)
    {
        $this->CardId = $cardId;

        return $this;
    }

    public function getCardId()
    {
        return $this->CardId;
    }

    public function setMinuteRdv($minuteRdv)
    {
        $this->minute_rdv = $minuteRdv;

        return $this;
    }

    public function getMinuteRdv()
    {
        return $this->minute_rdv;
    }
	
	public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    public function getCode()
    {
        return $this->code;
    }

    public function setCodeReduc($codeReduc)
    {
        $this->code_reduc = $codeReduc;

        return $this;
    }

    public function getCodeReduc()
    {
        return $this->code_reduc;
    }
    
    public function getCodeReducLabel()
    {
       if ($this->getCodeReduc())
          return number_format($this->getCodeReduc(), 2, '.', ' ').' €';
       else return '';
    }
}

src/FAPROD/BookingBundle/Form/BookingType.php
<?php
/**
 * FAPROD - Developpement et gestion de sites web
 *
 * CE DOCUMENT EST LA PROPRIETE EXCLUSIVE DE FAPROD,
 * TOUTE REPRODUCTION MEME PARTIELLE EST INTERDITE
 *
 *  @category   FAPROD
 *  @package    Website
 *  @author     Franck Alemany <franck.alemany@faprod.com>
 *  @copyright  2008-2015 FAPROD
 *  @license    http://www.faprod.com/ All rights reserved.
 *  @link       http://www.faprod.com
 */

namespace FAPROD\BookingBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BookingType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user', 'entity_hidden', array(
                'class' => 'FAPROD\UserBundle\Entity\User'))
			->add('day', 'date', array(
					'input'  => 'datetime',
					'widget' => 'choice', 
					'years'=> range(date("Y"),date("Y")+1), 
					'empty_value' => '', 
					'required' => true
				)
			)
            ->add('message', 'textarea', array(
                    'required'  => true,
                )
			)
            ->add('statut');
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FAPROD\BookingBundle\Entity\Booking',
        ));
    }
	
	public function getDefaultOptions(array $options)
    {
        return array(
			'data_class'      => 'FAPROD\BookingBundle\Entity\Booking',
        );
    }
    
    public function getName()
    {
        return 'faprod_bookingbundle_booking';
    }
}

src/FAPROD/BookingBundle/Resources/views/Booking/index.html.twig
{% extends "CoreBundle::layout.html.twig" %}

{% block body_content %}

<div class="container-fluid railway">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				{% if app.user.type == 2 %}
				<a href="{{ path('home_index') }}">{{ "Accueil"|trans }}</a> > <a href="{{ path('user_index') }}">{{ "Mon espace Pro"|trans }}</a> > {{ "Mes bookings"|trans }}
				{% else %}
				<a href="{{ path('home_index') }}">{{ "Accueil"|trans }}</a> > <a href="{{ path('user_show') }}">{{ "Mon profil"|trans }}</a> > {{ "Mes bookings"|trans }}
				{% endif %}
			</div>
		</div>
	</div>
</div>

<div class="container">
	
	<div class="row">
		<div class="hidden-xs col-sm-3 col-md-3 col-lg-3">
			{{ include("UserBundle:Partial:menu.html.twig") }}
		</div>
		<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
			
			<div class="panel panel-default">
				<div class="panel-heading">
				    <h3 class="panel-title">{{ "Mes bookings"|trans }}</h3>
				</div>
				<div class="panel-body">
					
					<div class="row">
						<div class="col-lg-12 box">
							
							{% if liste|length %}
					
					
								<table class="table">
									<thead>
										<tr class="entete">
											<th></th>
											<th>Prestation</th>
											{% if app.user.type == 1 %}
											<th>Pro</th>
											{% else %}
											<th>Cliente</th>
											{% endif %}
											<th>Date</th>
											<th>Heure</th>
											<th>Prix</th>
											<th>Statut</th>
										</tr>
									</thead>
									<tbody>
										{% for booking in liste %}
											<tr class="{% if booking.statut == 2 %}item-booking-avalider{% endif %}">
												<td><a href="{{ path('booking_show', {'booking_id': booking.id}) }}"><img src="{{ asset('images/loupe3.png') }}"></a></td>
												<td>{{ booking.offer }}</td>
												{% if app.user.type == 1 %}
												<td>{% if booking.seller %}{{ booking.seller.shortUsername }}{% endif %}</td>
												{% else %}
												<td>{% if booking.user %}{{ booking.user.shortUsername }}{% endif %}</td>
												{% endif %}
												<td>{{ booking.dateRdv('d/m/Y') }}</td>
												<td>{{ booking.heureRdvLabel }}</td>
												<td style="width:100px;">{{ booking.priceTtcLabel }}</td>
												<td>{{ booking.statutLabel }}</td>
											</tr>
										{% endfor %}
									</tbody>  
								</table>	

							
							{% else %}
							
								<div class="row">
									<div class="col-lg-12">
										{{ "Aucun booking pour le moment"|trans }}.<br/><br/>
									</div>
								</div>
							
							{% endif %}
							
							{% include 'CoreBundle::pagination.html.twig' with {'nbPages': nbPages, 'page': page, 'sort': sort, 'sens': sens, 'action': action} %}
					
						</div>
					</div>

		    	</div>
			</div>
		    
		</div>
	</div>

</div>
{% endblock %}

src/FAPROD/BookingBundle/Resources/views/Booking/show.html.twig
{% extends "CoreBundle::layout.html.twig" %}

{% block body_content %}

<div class="container-fluid railway">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				{% if app.user.type == 2 %}
				<a href="{{ path('home_index') }}">{{ "Accueil" }}</a> > <a href="{{ path('user_index') }}">{{ "Mon espace Pro"|trans }}</a> > {{ "Mes bookings"|trans }}
				{% else %}
				<a href="{{ path('home_index') }}">{{ "Accueil" }}</a> > <a href="{{ path('user_show') }}">{{ "Mon profil"|trans }}</a> > {{ "Mes bookings"|trans }}
				{% endif %}
			</div>
		</div>
	</div>
</div>

<div class="container">
	
	<div class="row">
		<div class="hidden-xs col-sm-3 col-md-3 col-lg-3">
		
			{{ include("UserBundle:Partial:menu.html.twig") }}
			
		</div>
		<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">{{ "Mon booking"|trans }}</h3>
				</div>
				<div class="panel-body">
				
					<h3 style="margin-top:0px;">{{ booking.statutLabel }}</h3>
					
					{% if booking.statut == 1 %}
						{% if app.user.type == 1 %}
							<p><b>Vous devez effectuer le paiement afin de confirmer la réservation</b></p>
						{% else %}
							<p><b>La cliente doit effectuer le paiement afin de confirmer la réservation</b></p>
						{% endif %}
					{% endif %}
					{% if booking.statut == 2 %}
						{% if app.user.type == 1 %}
							<p><b>Le paiement est effectué, la réservation doit maintenant être validée par votre Beauty Artist</b></p>
						{% else %}
							<p><b>Le paiement est effectué, vous devez maintenant valider la réservation</b></p>
						{% endif %}
					{% endif %}
					{% if booking.statut == 3 %}
						<p><b>La prestation sera effectuée le {{ booking.dateRdv('d/m/Y') }} à {{ booking.heureRdvLabel }}</b></p>
					{% endif %}
					{% if booking.statut == 4 %}
						{% if app.user.type == 1 %}
							<p><b>La prestation est effectuée, vous devez laisser une note et avis</b></p>
						{% else %}
							<p><b>La prestation est effectuée, la cliente doit laisser une note et avis</b></p>
						{% endif %}
					{% endif %}
							
					<table class="table table-condensed table_white">
						<tbody>
							<tr>
								<th style="width:20%;">{{ "Prestation"|trans }}</th>
								<td>{{ booking.offer }}</td>
							</tr>
							<tr>
								<th>{{ "Date"|trans }}</th>
								<td>{{ booking.dateRdv('d/m/Y') }}</td>
							</tr>
							<tr>
								<th>{{ "Heure"|trans }}</th>
								<td>{{ booking.heureRdvLabel }}</td>
							</tr>
							<tr>
								<th>{{ "Description"|trans }}</th>
								<td>{{ booking.offer.description|raw }}</td>
							</tr>
							<tr>
								<th>{{ "Durée"|trans }}</th>
								<td>{{ booking.offer.dureeLabel }}</td>
							</tr>
							<tr>
								<th>{{ "Photos"|trans }}</th>
								<td>
									<ul class="liste-photo">
									{% for image in booking.offer.images %}
										<li><a rel="facebox" href="{{ image.urlzoom }}"><img src="{{ image.url }}"/></a></li>
									{% endfor %}
									</ul>
								</td>
							</tr>
							{#<tr>
								<th>{{ "Prix"|trans }}</th>
								<td>{{ booking.priceLabel }}</td>
							</tr>#}
							{% if booking.code %}
							<tr>
								<th>{{ "Code de réduction"|trans }}</th>
								<td>{{ booking.code }}</td>
							</tr>
							<tr>
								<th>{{ "Réduction"|trans }}</th>
								<td>- {{ booking.codeReducLabel }}</td>
							</tr>
							{% endif %}
							<tr>
								<th>TVA sur frais de service</th>
								<td>{{ booking.tvaLabel }}</td>
							</tr>
							<tr>
								<th>{{ "Total"|trans }}</th>
								<td>{{ booking.priceTtcLabel }}</td>
							</tr>
						</tbody>
						<thead>
							<tr>
								<td colspan="2" class="text-center">
									{% if booking.statut == 1 and app.user.type == 1 %}
										<a  class="btn btn-warning btn-lg" href="javascript:void(0);" data-toggle="modal" data-target="#popupajaxModal" title="{{ "Payer cette réservation"|trans }}" data-title="{{ "Payer cette réservation"|trans }}" data-whatever="{{ path('booking_payer', {'booking_id' : booking.id }) }}"><span class="glyphicon glyphicon-hand-up"></span>&nbsp;&nbsp;{{ "Payer cette réservation"|trans }}</a>
										<button>Supprimer</button>
									{% endif %}
									{% if booking.statut == 2 and app.user.type == 2 %}
										<a href="{{ path('booking_accept', {'booking_id' : booking.id }) }}" class="btn btn-warning btn-lg"><span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;&nbsp;{{ "Confirmer cette réservation"|trans }}</a>
									{% endif %}
									{% if booking.statut == 2 and app.user.type == 2 %}
										&nbsp;&nbsp;<a href="{{ path('booking_refuse', {'booking_id' : booking.id }) }}" class="btn btn-warning btn-lg"><span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;&nbsp;{{ "Annuler cette réservation"|trans }}</a>
									{% endif %}
									{% if booking.statut == 4 and app.user.type == 1 %}
										<a  class="btn btn-warning btn-lg" href="javascript:void(0);" data-toggle="modal" data-target="#popupajaxModal" title="{{ "Ajouter une évaluation"|trans }}" data-title="{{ "Ajouter une évaluation"|trans }}" data-whatever="{{ path('booking_note', {'booking_id' : booking.id }) }}"><span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;&nbsp;{{ "Ajouter une évaluation"|trans }}</a>
									{% endif %}
								</td>
							</tr>
						</thead>
					</table>
				</div>
				{% if app.user.type == 1 and booking.seller %}
				<div class="panel-heading">
					<h3 class="panel-title">{{ "Beauty Artist"|trans }}</h3>
				</div>
				<div class="panel-body">

					<table class="table table-condensed table_white">
						<tbody>
							<tr>
							  <th>{{ "Photo"|trans }}</th>
							  <td colspan="3">
								{% if booking.seller.image is not null %}
									<a rel="facebox" href="{{ booking.seller.image.urlZoom }}"><img class="img-thumbnail" src="{{ booking.seller.image.url }}"/></a>
								{% endif %}
							  </td>
							</tr>
							<tr>
								<th style="width:20%;">{{ "Beauty Artist"|trans }}</th>
								<td>
									{{ booking.seller.shortUsername }}
								</td>
							</tr>
							{% if booking.statut >= 2 %}
							<tr>
								<th style="width:20%;">{{ "Portable"|trans }}</th>
								<td>{{ booking.seller.phoneLabel }}</td>
							</tr>
							{% endif %}
						</tbody>
						<tfoot>
							<tr>
								<th colspan="2" class="text-center">
									{% if booking.statut > 1 %}
										 <a class="btn btn-primary" href="{{ path('message_newdiscussion', {'destinataire_id' : booking.seller.id }) }}"><span class="glyphicon glyphicon-send"></span> &nbsp;&nbsp;{{ "Envoyer un message à"|trans }} {{ booking.seller.shortUsername }}</a>
									{% endif %}
								</th>
							</tr>
						</tfoot>
					</table>
				
				</div>
				
				{% elseif booking.user %}
				
				<div class="panel-heading">
					<h3 class="panel-title">{{ "La cliente"|trans }}</h3>
				</div>
				<div class="panel-body">
				
					<table class="table table-condensed table_white">
						<tbody>
							<tr>
							  <th>{{ "Photo"|trans }}</th>
							  <td colspan="3">
								{% if booking.user.image is not null %}
									<a rel="facebox" href="{{ booking.user.image.urlZoom }}"><img class="img-thumbnail" src="{{ booking.user.image.url }}"/></a>
								{% endif %}
							  </td>
							</tr>
							<tr>
								<th style="width:20%;">{{ "Prénom"|trans }}</th>
								<td colspan="3">
									{{ booking.user.shortUsername }}
								</td>
							</tr>
							{% if booking.statut >= 2 %}
							<tr>
							  <th>{{ "Adresse"|trans }}</th>
							  <td>{{ booking.user.address1 }}</td>
							  <th style="width:20%;">{{ "Complément"|trans }}</th>
							  <td>{{ booking.user.address2 }}</td>
							</tr>
							<tr>
							  <th>{{ "Code postal"|trans }}</th>
							  <td>{{ booking.user.postalCode }}</td>
							  <th>{{ "Ville"|trans }}</th>
							  <td>{{ booking.user.city }}</td>
							</tr>
							<tr>
							  <th>{{ "Fixe"|trans }}</th>
							  <td>{{ booking.user.phone }}</td>
							  <th>{{ "Portable"|trans }}</th>
							  <td>{{ booking.user.mobile }}</td>
							</tr>
							{% endif %}
							<tr>
							  <th>{{ "Cheveux"|trans }}</th>
							   <td colspan="3">{{ booking.user.cheveuxLabel }}</td>
							</tr>
							<tr>
							  <th>{{ "Peau"|trans }}</th>
							   <td colspan="3">
								    <ul>
									{% for competence in booking.user.peau %}
										<li style="margin-right:10px;display:inline;">
										{% if competence.couleurPeau %}
										<div class="img-circle img-thumbnail" style="width:50px;height:50px;background-color:#{{ competence.couleurPeau }}"></div>
										{% else %}
										{{ competence.title }}
										{% endif %}
										</li>
									{% endfor %}
									</ul>
							   </td>
							</tr>
							<tr>
							  <th>{{ "Preferences"|trans }}</th>
							   <td colspan="3">{{ booking.user.preferencesLabel }}</td>
							</tr>
							<tr>
								<th>{{ "Autres photos"|trans }}</th>
								<td colspan="3">
									<ul class="liste-photo">
									{% for image in booking.user.images %}
										<li><a rel="facebox" href="{{ image.urlZoom }}"><img class="img-thumbnail" src="{{ image.url }}"/></a></li>
									{% endfor %}
									</ul>
								</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<th colspan="4" class="text-center">
									{% if booking.statut > 1 %}
										 <a class="btn btn-primary" href="{{ path('message_newdiscussion', {'destinataire_id' : booking.user.id }) }}"><span class="glyphicon glyphicon-send"></span> &nbsp;&nbsp;{{ "Envoyer un message à"|trans }} {{ booking.user.shortUsername }}</a>
									{% endif %}
								</th>
							</tr>
						</tfoot>
					</table>
				
				</div>
				{% endif %}

					
				<div class="row">
					<div class="col-lg-12">
						<a style="margin:30px;" class="btn btn-primary" href="{{ path('booking_index') }}"><span>{{ "Retour"|trans }}</span></a>
					</div>
				</div>
						
					

			</div>
		    
		</div>
	</div>

</div>
{% endblock %}

src/FAPROD/BookingBundle/Resources/views/Booking/show_booking.html.twig
<div class="row popup_booking">
	<div class="col-lg-12" style="overflow-y:auto;max-height:349px;">
	
		{% if liste|length %}

			<table class="table table-condensed table_popup">
				<thead>
					<tr class="entete">
						<th></th>
						<th>Prestation</th>
						{% if app.user.type == 1 %}
						<th>Pro</th>
						{% else %}
						<th>Cliente</th>
						{% endif %}
						<th>Date</th>
						<th>Heure</th>
						<th style="width:80px;">Prix</th>
						<th>Statut</th>
					</tr>
				</thead>
				<tbody>
					{% for booking in liste %}
						<tr class="item{% if loop.index is divisibleby(2) %}1{% endif %}">
							<td><a href="{{ path('booking_show', {'booking_id': booking.id}) }}"><img src="{{ asset('images/loupe3.png') }}"></a></td>
							<td>{{ booking.offer }}</td>
							{% if app.user.type == 1 %}
							<td>{% if booking.seller %}{{ booking.seller.shortUsername }}{% endif %}</td>
							{% else %}
							<td>{% if booking.user %}{{ booking.user.shortUsername }}{% endif %}</td>
							{% endif %}
							<td>{{ booking.dateRdv('d/m/Y') }}</td>
							<td>{{ booking.heureRdvLabel }}</td>
							<td>{{ booking.priceTtcLabel }}</td>
							<td>{{ booking.statutLabel }}</td>
						</tr>
					{% endfor %}
				</tbody>  
			</table>	
			
			{% if liste|length >= 15  %}
			<p class="text-center">
				<a class="btn btn-primary" href="{{ path('booking_index') }}">{{ "Voir tout"|trans }}</a>
			</p>
			{% endif %}

		
		{% else %}
		
			<div class="row">
				<div class="col-lg-12 text-center">
					<br/><br/><br/><br/><br/>
					{{ "Aucun booking pour le moment"|trans }}.<br/><br/>
				</div>
			</div>
		
		{% endif %}
		
	</div>
</div>

src/FAPROD/BookingBundle/Resources/views/Booking/show_paiement.html.twig
<div class="row popup_booking">
	<div class="col-lg-12" style="overflow-y:auto;max-height:349px;">
	
		{% if liste|length %}
					

			<table class="table table-condensed table_popup">
				<thead>
					<tr class="entete">
						<th>Prestation</th>
						{% if app.user.type == 1 %}
						<th>Pro</th>
						{% else %}
						<th>Cliente</th>
						{% endif %}
						<th>Date</th>
						<th>Heure</th>
						<th>Prix</th>
						<th>Statut</th>
					</tr>
				</thead>
				<tbody>
					{% for booking in liste %}
						<tr class="item{% if loop.index is divisibleby(2) %}1{% endif %}">
							<td>{{ booking.offer }}</td>
							{% if app.user.type == 1 %}
							<td>{% if booking.seller %}{{ booking.seller.shortUsername }}{% endif %}</td>
							{% else %}
							<td>{% if booking.user %}{{ booking.user.shortUsername }}{% endif %}</td>
							{% endif %}
							<td>{{ booking.dateRdv('d/m/Y') }}</td>
							<td>{{ booking.heureRdvLabel }}</td>
							<td>{{ booking.priceTtcLabel }}</td>
							<td>{{ booking.statutLabel }}</td>
						</tr>
					{% endfor %}
				</tbody>  
			</table>	
			
			{% if liste|length >= 15  %}
			<p class="text-center">
				<a class="btn btn-primary" href="{{ path('booking_paiements') }}">{{ "Voir tout"|trans }}</a>
			</p>
			{% endif %}

		
		{% else %}
		
			<div class="row">
				<div class="col-lg-12">
					{{ "Aucun paiement pour le moment"|trans }}.<br/><br/>
				</div>
			</div>
		
		{% endif %}
		
	</div>
</div>