src/FAPROD/UserBundle/Entity/Image.php
<?php
/**
 * FAPROD - Developpement et gestion de sites web
 *
 * CE DOCUMENT EST LA PROPRIETE EXCLUSIVE DE FAPROD,
 * TOUTE REPRODUCTION MEME PARTIELLE EST INTERDITE
 *
 *  @category   FAPROD
 *  @package    Website
 *  @author     Franck Alemany <franck.alemany@faprod.com>
 *  @copyright  2008-2015 FAPROD
 *  @license    http://www.faprod.com/ All rights reserved.
 *  @link       http://www.faprod.com
 */
 
namespace FAPROD\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use FAPROD\CoreBundle\Lib\MyConst;
use FAPROD\CoreBundle\Lib\MyTools;

/**
 * @ORM\Entity(repositoryClass="FAPROD\UserBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="userimage")
 */
class Image
{
	const IMG_THUMB_WIDTH = 200;
	const IMG_THUMB_HEIGHT = 130;
	const IMG_PHOTO_WIDTH = 250;
	const IMG_PHOTO_HEIGHT = 150;
	const IMG_ZOOM_WIDTH = 600;
	const IMG_ZOOM_HEIGHT = 600;
	
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
      * @ORM\ManyToOne(targetEntity="User", inversedBy="images", cascade={"persist"})
      * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
      */
    private $user;
	
	/**
      * @ORM\ManyToOne(targetEntity="Offer", inversedBy="images", cascade={"persist"})
      * @ORM\JoinColumn(name="offer_id", referencedColumnName="id", onDelete="CASCADE")
      */
    private $offer;
    
    /**
     * @ORM\Column(name="filename", type="string", length=255, nullable=true)
     */
    private $filename;
    
    /**
     * @ORM\Column(name="ext", type="string", length=25, nullable=true)
     */
    private $ext;
    
    /**
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;
    
    private $tempFilename;
    private $tempFilename_photo;
    private $tempFilename_zoom;
    
    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;
    
    public function __toString()
    {
		return $this->getFilename();
    }
    
    public function __construct()
    {
    	$this->filename = 'no_image.png';
	}
    
    /**
	 *
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	 */
	public function updatedTimestamps()
	{
	    $this->setUpdatedAt(new \DateTime('now'));
	
	    if ($this->getCreatedAt() == null) {
	        $this->setCreatedAt(new \DateTime('now'));
	    }
	}
	
	public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    public function getUpdatedAt($format = '')
    {
        if($this->updated_at and $this->updated_at instanceof \DateTime and $format){
		    return $this->updated_at->format($format);
		} else {
    		return $this->updated_at;
    	}
    }

    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    public function getCreatedAt($format = '')
    {
    	if($this->created_at and $this->created_at instanceof \DateTime and $format){
		    return $this->created_at->format($format);
		} else {
    		return $this->created_at;
    	}
    }
    
    public function rotateImage($angle, $title){
    	
    	$new_filename = $title.'.'.date('is').MyTools::GetExtensionName($this->getFilename(), true);
    	
    	$tempFilename = $this->getUploadRootDir().'/thumb/u'.$this->id.'.'.$this->getFilename();
        //$tempFilename_photo = $this->getUploadRootDir().'/photo/photo_u'.$this->id.'.'.$this->getFilename();
        $tempFilename_zoom = $this->getUploadRootDir().'/zoom/zoom_u'.$this->id.'.'.$this->getFilename();
        
        $new_tempFilename = $this->getUploadRootDir().'/thumb/u'.$this->id.'.'.$new_filename;
        //$new_tempFilename_photo = $this->getUploadRootDir().'/photo/photo_u'.$this->id.'.'.$new_filename;
        $new_tempFilename_zoom = $this->getUploadRootDir().'/zoom/zoom_u'.$this->id.'.'.$new_filename;
        
        MyTools::rotateImage($tempFilename, $angle);
        //MyTools::rotateImage($tempFilename_photo, $angle);
        MyTools::rotateImage($tempFilename_zoom, $angle);
      
    	copy($tempFilename,$new_tempFilename);
		unlink($tempFilename);
		//copy($tempFilename_photo,$new_tempFilename_photo);
		//unlink($tempFilename_photo);
		copy($tempFilename_zoom,$new_tempFilename_zoom);
		unlink($tempFilename_zoom);
		
		$this->setFilename($new_filename);
	}

    public function upload($file_temp, $title)
    {

	  	if (file_exists($this->getUploadRootDir().'/temp/1_'.$file_temp) and file_exists($this->getUploadRootDir().'/temp/2_'.$file_temp)) {
	  	
	  		$filename = MyTools::stripText($title).'.'.date('is').MyTools::GetExtensionName($file_temp, true);
			$fichier_destination = 'u'.$this->id.'.'.$filename;
			  
		    // Si on avait un ancien fichier, on le supprime
		    $oldFile = $this->getUploadRootDir().'/thumb/'.$fichier_destination;
	        if (file_exists($oldFile)) {
	          unlink($oldFile);
	        }
	        //$oldFile = $this->getUploadRootDir().'/photo/photo_'.$fichier_destination;
	        //if (file_exists($oldFile)) {
	        //  unlink($oldFile);
	        //}
	        $oldFile = $this->getUploadRootDir().'/zoom/zoom_'.$fichier_destination;
	        if (file_exists($oldFile)) {
	          unlink($oldFile);
	        }
		      
		    copy($this->getUploadRootDir().'/temp/1_'.$file_temp, $this->getUploadRootDir().'/thumb/'.$fichier_destination);	      
		    //copy($this->getUploadRootDir().'/temp/2_'.$file_temp, $this->getUploadRootDir().'/photo/photo_'.$fichier_destination);
		    copy($this->getUploadRootDir().'/temp/2_'.$file_temp, $this->getUploadRootDir().'/zoom/zoom_'.$fichier_destination);
		    
		    //on efface le fichier temporaire
		    unlink($this->getUploadRootDir().'/temp/1_'.$file_temp);
		    unlink($this->getUploadRootDir().'/temp/2_'.$file_temp);
		    //unlink($this->getUploadRootDir().'/temp/3_'.$file_temp);
		    
		    $this->filename = $filename;
		    $this->ext = MyTools::GetExtensionName($file_temp, false);
      
  		}
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
      $new_tempFilename = $this->getUploadRootDir().'/thumb/u'.$this->id.'.'.$this->filename;
      $new_tempFilename_zoom = $this->getUploadRootDir().'/zoom/zoom_u'.$this->id.'.'.$this->filename;
		
      // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
      if (file_exists($new_tempFilename) and $this->filename != 'no_image.png') {
        // On supprime le fichier
        unlink($new_tempFilename);
      }
      if (file_exists($new_tempFilename_zoom) and $this->filename != 'no_image.png') {
        // On supprime le fichier
        unlink($new_tempFilename_zoom);
      }
    }

    public function getUploadDir()
    {
      // On retourne le chemin relatif vers l'image pour un navigateur
      return 'uploads';
    }

    public function getUploadRootDir()
    {
      // On retourne le chemin relatif vers l'image pour notre code PHP
      return __DIR__.'/../../../../'.MyConst::getWebDir().'/'.$this->getUploadDir();
    }
    
    public function getUrl()
    {
    	return MyConst::getSiteUrl().$this->getWebPath();
	}
	
	public function getUrlPhoto()
    {
    	return MyConst::getSiteUrl().$this->getWebPathPhoto();
	}
	
	public function getUrlZoom()
    {
    	return MyConst::getSiteUrl().$this->getWebPathZoom();
	}
  
    public function getWebPath()
    {
    	if ($this->getFilename() and $this->getFilename() != 'no_image.png'){
    		return $this->getUploadDir().'/thumb/'.'u'.$this->id.'.'.$this->getFilename();
    	} else {
    		return $this->getUploadDir().'/no_image.png';
    	}
    }
    
    public function getWebPathPhoto()
    {
    	if ($this->getFilename() and $this->getFilename() != 'no_image.png'){
    		return $this->getUploadDir().'/photo/photo_'.'u'.$this->id.'.'.$this->getFilename();
    	} else {
    		return $this->getUploadDir().'/no_image.png';
    	}
    }
    
    public function getWebPathZoom()
    {
    	if ($this->getFilename() and $this->getFilename() != 'no_image.png'){
    		return $this->getUploadDir().'/zoom/zoom_'.'u'.$this->id.'.'.$this->getFilename();
    	} else {
    		return $this->getUploadDir().'/no_image.png';
    	}
    }

    public function getId()
    {
        return $this->id;
    }

    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    public function getFilename()
    {
        return $this->filename;
    }

    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    public function getAlt()
    {
        return $this->alt;
    }

    public function setExt($ext)
    {
        $this->ext = $ext;

        return $this;
    }

    public function getExt()
    {
        return $this->ext;
    }

    public function setUser(\FAPROD\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setOffer(\FAPROD\UserBundle\Entity\Offer $offer = null)
    {
        $this->offer = $offer;

        return $this;
    }

    public function getOffer()
    {
        return $this->offer;
    }
}

src/FAPROD/UserBundle/Entity/Prestation.php
<?php
/**
 * FAPROD - Developpement et gestion de sites web
 *
 * CE DOCUMENT EST LA PROPRIETE EXCLUSIVE DE FAPROD,
 * TOUTE REPRODUCTION MEME PARTIELLE EST INTERDITE
 *
 *  @prestation   FAPROD
 *  @package    Website
 *  @author     Franck Alemany <franck.alemany@faprod.com>
 *  @copyright  2008-2015 FAPROD
 *  @license    http://www.faprod.com/ All rights reserved.
 *  @link       http://www.faprod.com
 */
 
namespace FAPROD\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Prezent\Doctrine\Translatable\Annotation as Prezent;
use Prezent\Doctrine\Translatable\Entity\AbstractTranslatable;

use FAPROD\CoreBundle\Lib\MyConst;

/**
 * @Gedmo\Tree(type="nested")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass="FAPROD\UserBundle\Entity\PrestationRepository")
 * @ORM\Table(name="prestation")
 */
class Prestation extends AbstractTranslatable
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @Prezent\Translations(targetEntity="PrestationTranslation")
     */
    protected $translations;
    
    /**
     * @Prezent\CurrentLocale
     */
    private $currentLocale;

    /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="no_order", type="integer", nullable=true)
     */
    private $no_order;

    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="level", type="integer", nullable=true)
     */
    private $level;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Prestation", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Prestation", mappedBy="parent")
     * @ORM\OrderBy({"no_order" = "ASC"})
     */
    private $children;
	
	/**
     * @ORM\Column(name="metiers", type="string", length=100, nullable=true)
     */
    private $metiers;
  
    /**
     * @ORM\Column(name="is_publish", type="boolean", nullable=true)
     */
    private $is_publish;
    
    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;

    // Getters et setters

    private $currentTranslation; // Cache current translation. Useful in Doctrine 2.4+
    

    public function __construct()
    {
		$this->translations = new ArrayCollection();
		$this->level = 0;
		$this->no_order = 1;
		$this->is_publish = true;
    }
    
    public static function getTranslationEntityClass()
    {
        return 'FAPROD\UserBundle\Entity\PrestationTranslation';
    }
    
    public function translate($locale = null)
    {
        if (null === $locale) {
            $locale = $this->currentLocale;
        }

        if (!$locale) {
            throw new \RuntimeException('No locale has been set and currentLocale is empty');
        }

        if ($this->currentTranslation && $this->currentTranslation->getLocale() === $locale) {
            return $this->currentTranslation;
        }

        if (!$translation = $this->translations->get($locale)) {
            $translation = new PrestationTranslation();
            $translation->setLocale($locale);
            $this->addTranslation($translation);
        }

        $this->currentTranslation = $translation;
        return $translation;
    }
    
    /**
	 *
	 * @ORM\PrePersist
	 * @ORM\PreUpdate
	 */
	public function updatedTimestamps()
	{
	    $this->setUpdatedAt(new \DateTime('now'));
	
	    if ($this->getCreatedAt() == null) {
	        $this->setCreatedAt(new \DateTime('now'));
	    }
	}
	
	public function __toString()
    {
    	$title = $this->getTitle();
    	if (!$title)$title = $this->getTitle('fr');
		return $title;
    }
	
	public function getTitle($locale = null)
    {
        return $this->translate($locale)->getTitle();
    }

    public function setTitle($title)
    {
        $this->translate()->setTitle($title);
        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setIsPublish($isPublish)
    {
        $this->is_publish = $isPublish;

        return $this;
    }

    public function getIsPublish()
    {
        return $this->is_publish;
    }
    
    public function getIsPublishLabel()
    {
        if ($this->getIsPublish())
        {
            return "Oui";
        } else {
            return "";
        }
    }

    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    public function getCreatedAt($format = '')
    {
    	if($this->created_at and $this->created_at instanceof \DateTime and $format){
		    return $this->created_at->format($format);
		} else {
    		return $this->created_at;
    	}
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    public function getUpdatedAt($format = '')
    {
        if($this->updated_at and $this->updated_at instanceof \DateTime and $format){
		    return $this->updated_at->format($format);
		} else {
    		return $this->updated_at;
    	}
    }

    public function setNoOrder($noOrder)
    {
        $this->no_order = $noOrder;

        return $this;
    }

    public function getNoOrder()
    {
        return $this->no_order;
    }

    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    public function getLevel()
    {
        return $this->level;
    }

    public function setParent(\FAPROD\UserBundle\Entity\Prestation $parent = null)
    {
        $this->parent = $parent;

        return $this;
    }

    public function getParent()
    {
        return $this->parent;
    }

    public function addChild(\FAPROD\UserBundle\Entity\Prestation $children)
    {
        $this->children[] = $children;

        return $this;
    }

    public function removeChild(\FAPROD\UserBundle\Entity\Prestation $children)
    {
        $this->children->removeElement($children);
    }

    public function getChildren()
    {
        return $this->children;
    }
	
	public function getDescription($locale = null)
    {
        return $this->translate($locale)->getDescription();
    }

    public function setDescription($content)
    {
        $this->translate()->setDescription($content);
        return $this;
    }

    public function setMetiers($metiers)
    {
        $this->metiers = implode("_",$metiers);

        return $this;
    }

    public function getMetiers()
    {
        return $this->metiers ? explode("_",$this->metiers) : array();
    }
	
	public function getMetiersLabel()
    {
		$metiers_label = '';
		
		foreach ($this->getMetiers() as $metier) {
			$metiers_label .= MyConst::getMetierLabel($metier).', ';
		}
		
        return $metiers_label;
    }
}

src/FAPROD/UserBundle/Form/BankType.php
<?php

namespace FAPROD\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints as Assert;

class BankType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('owner_name')
            ->add('owner_address')
            ->add('postcode', 'text', array('attr' => array('maxlength' => 5)))
            ->add('city')
			->add('IBAN', 'text', array('constraints' => array(new Assert\Iban(array('message' => 'IBAN invalide')))))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
					        ));
    }
    
    public function getDefaultOptions(array $options)
	{
	    return array(
	    			);
	}

    public function getName()
    {
        return 'faprod_userbundle_bank';
    }
}

src/FAPROD/UserBundle/Resources/views/Form/bank.html.twig
{% form_theme form 'CoreBundle:Form:fields_errors.html.twig' %}

<form method="POST" {{ form_enctype(form) }} class="form-horizontal col-lg-10">
    {{ form_errors(form) }}
    <div class="row">
	    <div class="form-group">
	      {{ form_label(form.owner_name, "Titulaire du compte"|trans, {'label_attr': {'class': 'col-lg-5'}}) }}
	      <div class="col-lg-7">
	        {{ form_errors(form.owner_name) }}
	        {{ form_widget(form.owner_name, { 'attr': {'class': 'form-control'}}) }}
	      </div>
	    </div>
	</div>
	<div class="row">
	    <div class="form-group">
	      {{ form_label(form.owner_address, "Adresse du titulaire"|trans, {'label_attr': {'class': 'col-lg-5'}}) }}
	      <div class="col-lg-7">
	        {{ form_errors(form.owner_address) }}
	        {{ form_widget(form.owner_address, { 'attr': {'class': 'form-control'} }) }}
	      </div>
	    </div>
	</div>
	<div class="row">
	    <div class="form-group">
	      {{ form_label(form.city, "Ville"|trans, {'label_attr': {'class': 'col-lg-5'}}) }}
	      <div class="col-lg-7">
	        {{ form_errors(form.city) }}
	        {{ form_widget(form.city, { 'attr': {'class': 'form-control'} }) }}
	      </div>
	    </div>
	</div>
	<div class="row">
	    <div class="form-group">
	      {{ form_label(form.postcode, "Code postal"|trans, {'label_attr': {'class': 'col-lg-5'}}) }}
	      <div class="col-lg-7">
	        {{ form_errors(form.postcode) }}
	        {{ form_widget(form.postcode, { 'attr': {'class': 'form-control'} }) }}
	      </div>
	    </div>
	</div>
	<div class="row">
	    <div class="form-group">
	      {{ form_label(form.IBAN, "n° IBAN"|trans, {'label_attr': {'class': 'col-lg-5'}}) }}
	      <div class="col-lg-7">
	        {{ form_errors(form.IBAN) }}
	        {{ form_widget(form.IBAN, { 'attr': {'class': 'form-control'} }) }}
	      </div>
	    </div>
	</div>
	<div class="form-group">
		<div class="col-lg-12">
			<button class="pull-right btn btn-primary"><span class="glyphicon glyphicon-ok-sign"></span> {{ "Valider"|trans }}</button>
			<a class="btn btn-primary" href="{{ path('document_edit', {'document_id' : 0, 'type' : 2}) }}"><span>{{ "Télécharger mon RIB"|trans }}</span></a>
	   </div>
    </div>
{{ form_widget(form._token) }}
</form>

src/FAPROD/UserBundle/Resources/views/Form/document.html.twig
{% form_theme form 'CoreBundle:Form:fields_errors.html.twig' %}
{% form_theme form 'UserBundle:Form:fields.html.twig' %}

<form id="myform" method="POST" onsubmit="$(this).find(':button').attr('disabled', 'disabled');this.submit();return true;" {{ form_enctype(form) }} class="form-horizontal col-lg-12">
    
    <div class="row">
	    <div class="form-group">
		  <div class="col-lg-3">
			<label>{{ "Type de document"|trans }}</label> <b class="form-obligatoire">*</b>
		  </div>
	      <div class="col-lg-9">
	        {{ form_errors(form.type) }}
	        {{ form_widget(form.type, { 'attr': {'class': 'form-control'} }) }}
	      </div>
	    </div>
	</div>
	<div class="row">
	    <div class="form-group">
		  <div class="col-lg-3">
			<label>{{ "Document"|trans }}</label>
		  </div>
	      <div class="col-lg-9">
	        {{ form_errors(form.file) }}
	        {{ form_widget(form.file) }}
	      </div>
	    </div>
	</div>
	<div class="row">
		<div class="form-group">
			<div class="col-lg-12 text-center">
				<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign"></span> {{ "Enregistrer"|trans }}</button>
		   </div>
		</div>
	</div>
{{ form_widget(form._token) }}
</form>

src/FAPROD/UserBundle/Resources/views/Form/photos.html.twig
{% form_theme form 'CoreBundle:Form:fields_errors.html.twig' %}
{% form_theme form 'UserBundle:Form:fields.html.twig' %}

<form id="myform" method="POST" onsubmit="$(this).find(':button').attr('disabled', 'disabled');this.submit();return true;" {{ form_enctype(form) }} class="form-horizontal col-lg-12">
    
    <div class="row">
	    <div class="form-group">
	      <label class="col-lg-1">{{ "Photo"|trans }}</label>
	      <div class="col-lg-2" id="div_image_principale_old_img" style="min-height:140px;">
	      	{% if form.vars.value.image is not null %}
			 <img class="img-thumbnail" id="image_old_img" src="{{ form.vars.value.image.url }}"/>
			 <input type="hidden" id="image_old" name="image_old" value="{{ form.vars.value.image.filename }}">
			 {% if form.vars.value.image.filename != 'no_image.png' %}
			 	<div class="row">
		 			<div class="col-lg-12 text-center">
						 	<a title="{{ 'Rotation à droite'|trans }}" href="javascript:void(0);" onclick="rotationImg('div_image_principale_old_img','{{ form.vars.value.image.id }}','-90','1', '{{ form.vars.value.strippedName }}');"><img style="width:20px;height:20px;" src="{{ asset('images/template/img-droite.png') }}"></a>
							&nbsp;&nbsp;
							<a title="{{ 'Supprimer'|trans }}" href="javascript:void(0);" onclick="$('#image_principale_old').val('');$('#image_principale_old_img').hide();$(this).hide();"><img style="width:15px;height:15px;" src="{{ asset('images/template/image-supprimer.jpg') }}"></a>
							&nbsp;&nbsp;
							<a title="{{ 'Rotation à gauche'|trans }}" href="javascript:void(0);" onclick="rotationImg('div_image_principale_old_img','{{ form.vars.value.image.id }}','90','1', '{{ form.vars.value.strippedName }}');"><img style="width:20px;height:20px;" src="{{ asset('images/template/img-gauche.png') }}"></a>
					</div>
				 </div>
			 {% endif %}
			{% endif %}
		  </div>
	      <div class="col-lg-5">
	        <div id="upload_image_div" class="dropzone text-center">
			    <div class="dz-default dz-message">
					<p>{{ "Cliquez ici pour ajouter votre photo principale."|trans }}</p>
					<p>{{ "Mettez de préférence une photo de votre visage."|trans }}</p>
				</div>
			</div>
	      </div>
	    </div>
	</div>
	<div class="row">
		<div class="form-group">
		  <label class="col-lg-12">{{ "Autres photos : ajoutez ci-dessous des photos de vos cheveux et de votre peau"|trans }}</label>
		  <div class="col-lg-12">
			<div class="row">
			{% if form.vars.value.images is not null %}
			 {% for image in form.vars.value.images %}
				<div class="col-lg-2" id="div_img_{{image.id}}" style="min-height:130px;">
					<div class="row">
						<div class="col-lg-12 text-center">
							<img class="img-thumbnail" style="width:100px;height:100px;" id="images_old_img_{{ image.id }}" src="{{ image.url }}"/>
							<input type="hidden" id="images_old_{{ image.id }}" name="images_old[]" value="{{ image.id }}">
						</div>
					</div>
					{% if image.filename != 'no_image.png' %}
					<div class="row">
						<div class="col-lg-12 text-center">
							<a title="{{ 'Rotation à droite'|trans }}" href="javascript:void(0);" onclick="rotationImg('div_img_{{image.id}}','{{ image.id }}','-90','2', '{{ form.vars.value.strippedName }}');"><img style="width:20px;height:20px;" src="{{ asset('images/template/img-droite.png') }}"></a>
							&nbsp;&nbsp;
							<a title="{{ 'Supprimer'|trans }}" href="javascript:void(0);" onclick="$('#images_old_{{ image.id }}').val('');$('#images_old_img_{{ image.id }}').hide();$(this).hide();"><img style="width:15px;height:15px;" src="{{ asset('images/template/image-supprimer.jpg') }}"></a>
							&nbsp;&nbsp;
							<a title="{{ 'Rotation à gauche'|trans }}" href="javascript:void(0);" onclick="rotationImg('div_img_{{image.id}}','{{ image.id }}','90','2', '{{ form.vars.value.strippedName }}');"><img style="width:20px;height:20px;" src="{{ asset('images/template/img-gauche.png') }}"></a>
						</div>
					</div>
					{% endif %}
				</div>
			 {% endfor %}
			{% endif %}
			</div>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
		  <div class="col-lg-12">
			<div id="upload_images_div" class="dropzone">
				<div class="dz-default dz-message">

				</div>
				
				<p class="text-center">
				{{ "Ajoutez des photos de vos cheveux et de votre peau"|trans }}
				</p>
			</div>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<div class="col-lg-12 text-center">
				<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign"></span> {{ "Enregistrer"|trans }}</button>
		   </div>
		</div>
	</div>
</form>